import { getEnv } from "../lib/env";
import { createZip } from "../lib/zip";
import { exportDb, searchReplaceSQL, hardenAdminCredentialsSQL, getLocalTablePrefix, renameDatabasePrefixSQL } from "../lib/db";
import { log } from "../lib/logger";
import { existsSync } from "fs";
import { rm, mkdir, cp, writeFile } from "fs/promises";
import { join } from "path";
import crypto from "crypto";

const { prompt } = require('enquirer');

export default async function () {
    const env = await getEnv();
    log.info(`Starting ${env.PROJECT_SLUG} package build...`);
    
    const stagingDir = join(process.cwd(), ".staging");
    const stagingWpDir = join(stagingDir, "wordpress");
    
    // Clean staging
    if (existsSync(stagingDir)) {
        await rm(stagingDir, { recursive: true, force: true });
    }
    await mkdir(stagingDir, { recursive: true });
    
    log.info("Copying WordPress files to staging...");
    await cp(env.LOCAL_WP_PATH, stagingWpDir, { recursive: true });
    
    // Security cleanup
    const sampleConfig = join(stagingWpDir, "wp-config-sample.php");
    if (existsSync(sampleConfig)) {
        await rm(sampleConfig, { force: true });
    }
    
    log.info("Generating production wp-config.php...");
    
    // Generate cryptographically secure salts offline
    const saltKeys = [
        'AUTH_KEY',
        'SECURE_AUTH_KEY',
        'LOGGED_IN_KEY',
        'NONCE_KEY',
        'AUTH_SALT',
        'SECURE_AUTH_SALT',
        'LOGGED_IN_SALT',
        'NONCE_SALT'
    ];
    const salts = saltKeys
        .map(key => `define( '${key}', '${crypto.randomBytes(48).toString('base64').replace(/['\\]/g, '')}' );`)
        .join("\n");
    
    const wpConfigContent = `<?php
/**
 * Production WordPress Configuration
 * Auto-generated by ${env.PROJECT_SLUG}-cli
 */

define( 'DB_NAME', '${env.PROD_DB_NAME}' );
define( 'DB_USER', '${env.PROD_DB_USER}' );
define( 'DB_PASSWORD', '${env.PROD_DB_PASS}' );
define( 'DB_HOST', '${env.PROD_DB_HOST}' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

${salts}

$table_prefix = '${env.WP_TABLE_PREFIX}';

define( 'WP_HOME', '${env.PROD_URL}' );
define( 'WP_SITEURL', '${env.PROD_URL}' );
define( 'WP_DEBUG', false );
define( 'DISALLOW_FILE_EDIT', true );

if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}
require_once ABSPATH . 'wp-settings.php';
`;
    await writeFile(join(stagingWpDir, "wp-config.php"), wpConfigContent, "utf-8");
    
    log.info("Generating production .htaccess...");
    const htaccessContent = `# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress

# Security rules
<Files wp-config.php>
    order allow,deny
    deny from all
</Files>
Options -Indexes
`;
    await writeFile(join(stagingWpDir, ".htaccess"), htaccessContent, "utf-8");

    log.info("Configuring Zero-Touch SMTP plugin...");
    const muPluginsDir = join(stagingWpDir, "wp-content", "mu-plugins");
    if (!existsSync(muPluginsDir)) {
        await mkdir(muPluginsDir, { recursive: true });
    }
    const smtpConfigContent = `<?php
/**
 * Plugin Name: ${env.PROJECT_SLUG} Sovereign Mail Delivery
 * Description: Zero-touch PHPMailer SMTP auto-configuration.
 * Version: 1.0.0
 */
add_action( 'phpmailer_init', function( $phpmailer ) {
    $phpmailer->isSMTP();
    $phpmailer->Host       = '${env.SMTP_HOST}';
    $phpmailer->SMTPAuth   = true;
    $phpmailer->Port       = ${env.SMTP_PORT};
    $phpmailer->SMTPSecure = 'tls';
    $phpmailer->Username   = '${env.SMTP_USER}';
    $phpmailer->Password   = '${env.SMTP_PASS}';
    $phpmailer->From       = '${env.SMTP_USER}';
    $phpmailer->FromName   = '${env.PROJECT_SLUG}';
} );
`;
    await writeFile(join(muPluginsDir, `${env.PROJECT_SLUG}-smtp-config.php`), smtpConfigContent, "utf-8");

    const dbPrompt: any = await prompt({
        type: 'confirm',
        name: 'exportDb',
        message: 'Do you want to export the current local DB along with the zip file?'
    });

    const dateStr = new Date().toISOString().split("T")[0];
    let sqlFile: string | null = null;

    if (dbPrompt.exportDb) {
        log.info("Exporting and preparing database...");
        // Output separate side-by-side SQL file in working directory (NOT inside staging)
        sqlFile = join(process.cwd(), `${env.PROJECT_SLUG}-import-${dateStr}.sql`);
        await exportDb(env, sqlFile);
        
        // Handle Prefix Migration
        const localPrefix = await getLocalTablePrefix(env.LOCAL_WP_PATH);
        if (localPrefix !== env.WP_TABLE_PREFIX) {
            await renameDatabasePrefixSQL(sqlFile, localPrefix, env.WP_TABLE_PREFIX);
        }

        await searchReplaceSQL(sqlFile, env.LOCAL_URL, env.PROD_URL);
        await hardenAdminCredentialsSQL(sqlFile, env);
        log.success(`Database exported to separate SQL file: ${sqlFile}`);
    } else {
        log.info("Skipping database export...");
    }
    
    const zipName = `${env.PROJECT_SLUG}-cpanel-ready-${dateStr}.zip`;
    
    await createZip(env.SEVENZIP_PATH, stagingWpDir, zipName);
    
    log.info("Cleaning up staging...");
    await rm(stagingDir, { recursive: true, force: true });
    
    log.success(`Package created successfully: ${zipName}`);
    if (sqlFile) {
        log.success(`Side-by-side SQL import file created: ${sqlFile}`);
        log.info(`Upload ${zipName} via cPanel File Manager and import ${sqlFile} via phpMyAdmin.`);
    }
}
