import { getEnv } from "../lib/env";
import { createZip } from "../lib/zip";
import { exportDb, searchReplaceSQL, hardenAdminCredentialsSQL } from "../lib/db";
import { log } from "../lib/logger";
import { rmSync, mkdirSync, cpSync, writeFileSync, existsSync } from "fs";
import { join } from "path";

export default async function () {
    log.info("Starting Zero Sugar package build...");
    const env = await getEnv();
    
    const stagingDir = join(process.cwd(), ".staging");
    const stagingWpDir = join(stagingDir, "wordpress");
    
    // Clean staging
    if (existsSync(stagingDir)) {
        rmSync(stagingDir, { recursive: true, force: true });
    }
    mkdirSync(stagingDir, { recursive: true });
    
    log.info("Copying WordPress files to staging...");
    cpSync(env.LOCAL_WP_PATH, stagingWpDir, { recursive: true });
    
    // Security cleanup
    const sampleConfig = join(stagingWpDir, "wp-config-sample.php");
    if (existsSync(sampleConfig)) rmSync(sampleConfig);
    
    log.info("Generating production wp-config.php...");
    
    // Fetch fresh salts
    const saltsResponse = await fetch("https://api.wordpress.org/secret-key/1.1/salt/");
    const salts = await saltsResponse.text();
    
    const wpConfigContent = `<?php
/**
 * Production WordPress Configuration
 * Auto-generated by zero-sugar-cli
 */

define( 'DB_NAME', '${env.PROD_DB_NAME}' );
define( 'DB_USER', '${env.PROD_DB_USER}' );
define( 'DB_PASSWORD', '${env.PROD_DB_PASS}' );
define( 'DB_HOST', '${env.PROD_DB_HOST}' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

${salts}

$table_prefix = '${env.WP_TABLE_PREFIX}';

define( 'WP_HOME', '${env.PROD_URL}' );
define( 'WP_SITEURL', '${env.PROD_URL}' );
define( 'WP_DEBUG', false );
define( 'DISALLOW_FILE_EDIT', true );

if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}
require_once ABSPATH . 'wp-settings.php';
`;
    writeFileSync(join(stagingWpDir, "wp-config.php"), wpConfigContent);
    
    log.info("Generating production .htaccess...");
    const htaccessContent = `# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress

# Security rules
<Files wp-config.php>
    order allow,deny
    deny from all
</Files>
Options -Indexes
`;
    writeFileSync(join(stagingWpDir, ".htaccess"), htaccessContent);

    log.info("Configuring Zero-Touch SMTP plugin...");
    const muPluginsDir = join(stagingWpDir, "wp-content", "mu-plugins");
    if (!existsSync(muPluginsDir)) {
        mkdirSync(muPluginsDir, { recursive: true });
    }
    const smtpConfigContent = `<?php
/**
 * Plugin Name: ZEROSUGAR Sovereign Mail Delivery
 * Description: Zero-touch PHPMailer SMTP auto-configuration.
 * Version: 1.0.0
 */
add_action( 'phpmailer_init', function( $phpmailer ) {
    $phpmailer->isSMTP();
    $phpmailer->Host       = '${env.SMTP_HOST}';
    $phpmailer->SMTPAuth   = true;
    $phpmailer->Port       = ${env.SMTP_PORT};
    $phpmailer->SMTPSecure = 'tls';
    $phpmailer->Username   = '${env.SMTP_USER}';
    $phpmailer->Password   = '${env.SMTP_PASS}';
    $phpmailer->From       = '${env.SMTP_USER}';
    $phpmailer->FromName   = 'ZEROSUGAR';
} );
`;
    writeFileSync(join(muPluginsDir, "zs-smtp-config.php"), smtpConfigContent);

    const { prompt } = require('enquirer');
    const dbPrompt: any = await prompt({
        type: 'confirm',
        name: 'exportDb',
        message: 'Do you want to export the current local DB along with the zip file?'
    });

    if (dbPrompt.exportDb) {
        log.info("Exporting and preparing database...");
        const sqlFile = join(stagingWpDir, "zerosugar_import.sql");
        await exportDb(env, sqlFile);
        searchReplaceSQL(sqlFile, env.LOCAL_URL, env.PROD_URL);
        hardenAdminCredentialsSQL(sqlFile, env);
    } else {
        log.info("Skipping database export...");
    }
    
    const dateStr = new Date().toISOString().split("T")[0];
    const zipName = `zerosugar-cpanel-ready-${dateStr}.zip`;
    
    await createZip(env.SEVENZIP_PATH, stagingWpDir, zipName);
    
    log.info("Cleaning up staging...");
    rmSync(stagingDir, { recursive: true, force: true });
    
    log.success(`Package created successfully: ${zipName}`);
}
